language: cpp

compiler:
    - gcc

dist: xenial

before_install:
    - sudo apt-get install zlib1g-dev libmxml-dev libfftw3-dev dssi-dev libfltk1.3-dev fluid libxpm-dev
    - sudo apt-get install liblo-dev
    - sudo apt-get install libsndio-dev


script:
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest --output-on-failure
